name: CI â€“ Umlops Pipeline

on:
  push:
    paths:
      - 'mlops_pipeline/**'
  workflow_dispatch:

jobs:
  run-mlops-pipeline:
    uses: ./.github/workflows/ci-template.yml
    with:
      pipeline-dir: mlops_pipeline
      environment: dev
      tools: '["build","test","deploy"]'
